"""
Quest models.

Quest — one generated fill-in-the-blank question instance.

  Built at runtime from a LanguageContent row (or LLM generation):
    question_fi  → Finnish sentence with target replaced by ....
    question_en  → English sentence with target replaced by ....
    options      → 4 lowercase choices (1 correct + 3 distractors), shuffled
    correct_answer → never returned to the player before submission

  source field distinguishes how the quest was generated:
    "wordbank" → picked from language_content table (fast, default)
    "llm"      → generated by LLM fallback (when wordbank has no good match)

QuestSubmission — records one player answer.

  Persisted after every /quests/submit call.
  Used for tracking player history and adaptive difficulty (future work).
"""

import uuid

from sqlalchemy import Boolean, Float, Integer, String, Text
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class Quest(Base):
    __tablename__ = "quests"

    # Which LanguageContent row this was built from (None for LLM-generated)
    content_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True, index=True
    )

    # "wordbank" | "llm"
    source: Mapped[str] = mapped_column(String(32), nullable=False, default="wordbank")

    # Finnish sentence with target blanked e.g. "Haluaisin kupillisen ...., kiitos."
    question_fi: Mapped[str] = mapped_column(Text, nullable=False)

    # English sentence with target blanked
    question_en: Mapped[str] = mapped_column(Text, nullable=False)

    # 4 lowercase options already shuffled e.g. ["kahvia", "teetä", "vettä", "maitoa"]
    options: Mapped[list] = mapped_column(ARRAY(String), nullable=False)

    # The correct option — NEVER returned to the player before submission
    correct_answer: Mapped[str] = mapped_column(String(256), nullable=False)

    difficulty: Mapped[float] = mapped_column(Float, nullable=False)

    def __repr__(self) -> str:
        return f"<Quest source={self.source} correct='{self.correct_answer}'>"


class QuestSubmission(Base):
    __tablename__ = "quest_submissions"

    quest_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )

    # user_id comes from Node.js JWT, stored as string
    user_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)

    given_answer: Mapped[str] = mapped_column(String(256), nullable=False)
    is_correct: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # XP earned this submission
    xp_earned: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Pack quality score 0.0-1.0 — determines card rarity when a pack is awarded
    pack_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    def __repr__(self) -> str:
        return f"<QuestSubmission user={self.user_id} correct={self.is_correct}>"
