"""
Challenge service — FULL CODE.

Manages the full lifecycle of a boss fight session:
  - start_challenge()      creates the session, fetches questions from Quest Service
  - process_action()       scores an answer, updates HP, advances the turn
  - get_next_question()    returns the next ChallengeQuestion from the local queue
  - get_session()          fetches a session by ID

Key architecture note:
  Questions are NOT generated directly from a DB here.
  At fight start, challenge_service calls Quest Service (8001) via HTTP
  and mirrors all questions into the local challenge_questions table as
  ChallengeQuestion rows. This makes the fight self-contained mid-session —
  no calls back to Quest Service after start.

Boss fight loop per turn:
  - Correct → player deals damage (best card power in deck)
  - Wrong   → AI deals flat damage + scenario flavour taunt
  - Ends when either HP hits 0 or all turns are exhausted

KELA boss:
  - Questions generated by Claude LLM (llm_boss module)
  - Stored as ChallengeQuestion rows with source="llm"
  - Minimum deck size enforced before start
"""

import random
import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.core.http_client import fetch_quest_question
from app.data.battle_scenarios import SCENARIOS
from app.models.challenge_session import ChallengeAction, ChallengeSession, ChallengeStatus
from app.models.challenge_question import ChallengeQuestion
from app.services import llm_boss

settings = get_settings()

# Rarity → battle power (mirrors Card Service values so damage is consistent)
RARITY_POWER: dict[str, int] = {
    "Common":    5,
    "Uncommon":  10,
    "Rare":      20,
    "Epic":      35,
    "Legendary": 50,
}


async def start_challenge(
    db: AsyncSession,
    user_id: str,
    scenario: str,
    deck: list[dict],
) -> ChallengeSession:
    """
    Create a new boss fight session and build the full question queue upfront.

    For normal scenarios: calls Quest Service via HTTP, mirrors questions locally.
    For kela_boss: calls Claude LLM, stores questions locally.
    """
    if scenario not in SCENARIOS:
        raise ValueError(
            f"Unknown scenario '{scenario}'. "
            f"Valid options: {list(SCENARIOS.keys())}"
        )

    scenario_data = SCENARIOS[scenario]

    if scenario_data.get("uses_llm"):
        min_size = scenario_data.get("min_deck_size", settings.KELA_MIN_DECK_SIZE)
        if len(deck) < min_size:
            raise ValueError(
                f"KELA requires at least {min_size} cards in your deck. "
                f"You only have {len(deck)}."
            )

    questions = await _build_question_queue(db, scenario, scenario_data, deck)

    if not questions:
        raise ValueError(
            "Could not build question queue for this boss fight. "
            "Make sure the Quest Service is running and seeded."
        )

    question_ids = [str(q.id) for q in questions]

    session = ChallengeSession(
        id=uuid.uuid4(),
        user_id=user_id,
        scenario=scenario,
        status=ChallengeStatus.ACTIVE,
        player_hp=settings.PLAYER_MAX_HP,
        ai_hp=settings.AI_MAX_HP,
        current_turn=1,
        question_queue=question_ids,
        deck=deck,
        xp_earned=0,
        bonus_packs=0,
    )

    db.add(session)
    await db.flush()
    return session


async def process_action(
    db: AsyncSession,
    session: ChallengeSession,
    question_id: uuid.UUID,
    given_answer: str,
) -> tuple[ChallengeSession, dict]:
    """
    Process one player turn.

    Scores the answer, updates HP, logs the action, checks end conditions.
    Returns the updated session and an action summary dict for the response.
    """
    if session.status != ChallengeStatus.ACTIVE:
        raise ValueError("This boss fight is already over.")

    result = await db.execute(
        select(ChallengeQuestion).where(ChallengeQuestion.id == question_id)
    )
    question = result.scalar_one_or_none()
    if question is None:
        raise ValueError(f"Question {question_id} not found.")

    is_correct, feedback, xp = _score_answer(question.correct_answer, given_answer)

    damage_dealt = 0
    damage_taken = 0
    ai_flavour = None

    if is_correct:
        damage_dealt = _best_card_power(session.deck)
        session.ai_hp = max(0, session.ai_hp - damage_dealt)
    else:
        damage_taken = settings.AI_FLAT_DAMAGE
        session.player_hp = max(0, session.player_hp - damage_taken)
        ai_flavour = _pick_flavour(session.scenario)

    session.xp_earned += xp
    session.current_turn += 1

    action = ChallengeAction(
        id=uuid.uuid4(),
        session_id=session.id,
        turn=session.current_turn - 1,
        question_id=question_id,
        given_answer=given_answer,
        is_correct=is_correct,
        damage_dealt=damage_dealt,
        damage_taken=damage_taken,
    )
    db.add(action)

    max_turns = len(session.question_queue)
    _check_end_conditions(session, max_turns)

    await db.flush()

    action_summary = {
        "turn": session.current_turn - 1,
        "question_id": str(question_id),
        "given_answer": given_answer,
        "correct_answer": question.correct_answer,
        "is_correct": is_correct,
        "feedback": feedback,
        "damage_dealt": damage_dealt,
        "damage_taken": damage_taken,
        "player_hp": session.player_hp,
        "ai_hp": session.ai_hp,
        "ai_flavour": ai_flavour,
    }

    return session, action_summary


async def get_next_question(
    db: AsyncSession,
    session: ChallengeSession,
) -> ChallengeQuestion | None:
    """
    Return the next ChallengeQuestion based on the current turn index.
    Returns None when the fight is over or all turns are exhausted.
    """
    if session.status != ChallengeStatus.ACTIVE:
        return None

    queue: list[str] = session.question_queue
    turn_index = session.current_turn - 1

    if turn_index >= len(queue):
        return None

    question_id = uuid.UUID(queue[turn_index])
    result = await db.execute(
        select(ChallengeQuestion).where(ChallengeQuestion.id == question_id)
    )
    return result.scalar_one_or_none()


async def get_session(
    db: AsyncSession,
    session_id: uuid.UUID,
) -> ChallengeSession | None:
    """Fetch a boss fight session by ID."""
    result = await db.execute(
        select(ChallengeSession).where(ChallengeSession.id == session_id)
    )
    return result.scalar_one_or_none()


# ── Private helpers ────────────────────────────────────────────────────────────

async def _build_question_queue(
    db: AsyncSession,
    scenario: str,
    scenario_data: dict,
    deck: list[dict],
) -> list[ChallengeQuestion]:
    """
    Build the full list of ChallengeQuestion rows for this boss fight.

    KELA: delegates to llm_boss, which calls Claude and stores questions locally.
    Others: calls Quest Service via HTTP, mirrors questions as ChallengeQuestion rows.
    """
    if scenario_data.get("uses_llm"):
        return await llm_boss.generate_kela_questions(db, deck)

    num_turns = scenario_data["turns"]
    tag = scenario_data["tag"]
    diff_min = scenario_data["difficulty_min"]
    diff_max = scenario_data["difficulty_max"]

    difficulties = _spread_difficulties(diff_min, diff_max, num_turns)
    questions: list[ChallengeQuestion] = []

    for diff in difficulties:
        raw = None

        # Try with scenario tag + difficulty
        try:
            raw = await fetch_quest_question(scenario_tag=tag, difficulty_target=diff)
        except Exception:
            pass

        # Fallback: try with just scenario tag
        if raw is None:
            try:
                raw = await fetch_quest_question(scenario_tag=tag)
            except Exception:
                pass

        # Last resort: any question at all
        if raw is None:
            try:
                raw = await fetch_quest_question()
            except Exception:
                continue

        if raw:
            cq = ChallengeQuestion(
                id=uuid.uuid4(),
                external_id=uuid.UUID(raw["id"]),
                source="quest_service",
                question_fi=raw["question_fi"],
                question_en=raw["question_en"],
                options=raw["options"],
                correct_answer=raw["correct_answer"],
                difficulty=raw["difficulty"],
            )
            db.add(cq)
            questions.append(cq)

    await db.flush()
    return questions


def _spread_difficulties(lo: float, hi: float, n: int) -> list[float]:
    """Return n difficulty values spread from lo to hi with slight random jitter."""
    if n <= 1:
        return [lo]
    step = (hi - lo) / (n - 1)
    values = [lo + i * step for i in range(n)]
    jitter = step * 0.2
    return [
        max(lo, min(hi, v + random.uniform(-jitter, jitter)))
        for v in values
    ]


def _score_answer(correct_answer: str, given_answer: str) -> tuple[bool, str, int]:
    """Score a multiple choice answer. Returns (is_correct, feedback, xp_earned)."""
    is_correct = correct_answer.strip() == given_answer.strip()
    feedback = "Correct!" if is_correct else f'The answer was "{correct_answer}".'
    xp = 10 if is_correct else 2
    return is_correct, feedback, xp


def _best_card_power(deck: list[dict]) -> int:
    """Return the highest power value among the player's cards. Fallback: 10."""
    if not deck:
        return 10
    powers = []
    for card in deck:
        power = card.get("power")
        if power is None:
            power = RARITY_POWER.get(card.get("rarity", "Common"), 5)
        powers.append(power)
    return max(powers)


def _pick_flavour(scenario: str) -> str:
    """Pick a random wrong-answer taunt for the given scenario."""
    taunts = SCENARIOS.get(scenario, {}).get("ai_wrong_answer", ["..."])
    return random.choice(taunts)


def _check_end_conditions(session: ChallengeSession, max_turns: int) -> None:
    """Update session status if the boss fight should end."""
    scenario_data = SCENARIOS[session.scenario]

    if session.ai_hp <= 0:
        session.status = ChallengeStatus.WON
        session.bonus_packs = scenario_data["bonus_packs"]
        session.xp_earned += scenario_data["xp_reward"]
        return

    if session.player_hp <= 0:
        session.status = ChallengeStatus.LOST
        return

    if session.current_turn > max_turns:
        if session.player_hp > session.ai_hp:
            session.status = ChallengeStatus.WON
            session.bonus_packs = max(1, scenario_data["bonus_packs"] - 1)
            session.xp_earned += scenario_data["xp_reward"] // 2
        elif session.ai_hp > session.player_hp:
            session.status = ChallengeStatus.LOST
        else:
            session.status = ChallengeStatus.DRAW
