"""
KELA LLM Boss — generates Finnish bureaucratic boss fight questions.

The KELA boss is the hardest challenge in Lingo Deck.
Every question is generated by an LLM based on the player's actual deck —
if you collected the word "perustoimeentulotuki" you will face it in the fight.

Generation flow:
  1. Receive player's deck (list of cards with Finnish words)
  2. Send all deck words to LLM in one request
  3. LLM returns one KELA-office question per card
  4. Validate each question (target must appear in sentence)
  5. Randomly drop 2 so the player can't memorise the order
  6. Shuffle the remainder
  7. Persist as ChallengeQuestion rows with source="llm"
"""

import json
import random
import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.challenge_question import ChallengeQuestion
from app.services import llm_client

KELA_SYSTEM = """You are a Finnish language learning content generator
specialised in KELA (Finnish Social Insurance Institution) bureaucratic Finnish.
KELA language: formal register, passive voice, partitive case, long compound nouns.
Respond with valid JSON only. No markdown, no explanation."""

KELA_PROMPT = """The player's deck contains these Finnish words:
{word_list}

Generate exactly {count} fill-in-the-blank questions, one per word.
Each question must be set in a realistic KELA office scenario
(filling forms, asking about benefits, dealing with bureaucracy).

Rules:
1. target_fi must appear EXACTLY in sentence_fi
2. Use the grammatically correct inflected form if needed
3. 3 distractors must be real Finnish words, plausible but clearly wrong
4. All 4 options should be the same word class
5. Vary difficulty — mix simpler and harder sentences

Return ONLY this JSON:
{{
  "questions": [
    {{
      "sentence_fi": "Finnish KELA sentence",
      "sentence_en": "English translation",
      "target_fi": "exact word to blank",
      "target_en": "English of target",
      "distractor_1_fi": "wrong option 1",
      "distractor_2_fi": "wrong option 2",
      "distractor_3_fi": "wrong option 3"
    }}
  ]
}}"""

# Taunts shown to the player on wrong answers — KELA flavour
KELA_TAUNTS = [
    "Form rejected. Please refile within 14 days.",
    "The system requires the correct case suffix.",
    "Your application is under processing. Duration: undefined.",
    "A letter has been sent to your address. Good luck reading it.",
    "Please visit your nearest KELA office. Bring everything.",
    "Missing attachment. Application paused.",
]

VICTORY_TEXT = "Hakemus hyväksytty! Application approved. A true Finnish miracle."
DEFEAT_TEXT = "Hakemus hylätty. Your application has been rejected. Reason: insufficient Finnish. Please try again in 6-8 weeks."


async def generate_questions(
    db: AsyncSession,
    deck: list[dict],
) -> list[ChallengeQuestion]:
    """
    Generate KELA boss questions for the player's deck.

    Returns a shuffled list of ChallengeQuestion rows.
    Drops 2 randomly so the player can't memorise the question order.
    """
    word_list = "\n".join(
        f"- {card['word_fi']} (rarity: {card['rarity']})"
        for card in deck
    )

    prompt = KELA_PROMPT.format(word_list=word_list, count=len(deck))

    # Try up to 3 times in case the LLM returns bad JSON
    for attempt in range(3):
        try:
            raw = await llm_client.generate_kela_json(prompt, KELA_SYSTEM)
            raw_questions = raw.get("questions", [])
            break
        except (ValueError, Exception) as e:
            if attempt == 2:
                raise RuntimeError(f"KELA LLM failed after 3 attempts: {e}") from e

    questions = await _persist(db, raw_questions)

    # Drop 2 randomly — deck_size - 2 questions remain
    # e.g. 8 cards → 6 questions, so player can't brute-force by card order
    if len(questions) > 2:
        questions = random.sample(questions, len(questions) - 2)

    random.shuffle(questions)
    return questions


async def _persist(
    db: AsyncSession,
    raw_questions: list[dict],
) -> list[ChallengeQuestion]:
    """Convert LLM output into ChallengeQuestion rows. Skips invalid entries."""
    questions: list[ChallengeQuestion] = []

    for raw in raw_questions:
        try:
            sentence_fi = raw["sentence_fi"]
            target_fi   = raw["target_fi"]
            target_en   = raw["target_en"]
            d1 = raw["distractor_1_fi"]
            d2 = raw["distractor_2_fi"]
            d3 = raw["distractor_3_fi"]
        except KeyError as e:
            # Skip malformed entries rather than crashing the whole fight
            print(f"[kela_boss] Skipping malformed question, missing: {e}")
            continue

        # Validate target appears in sentence
        if target_fi.lower() not in sentence_fi.lower():
            print(f"[kela_boss] Skipping: '{target_fi}' not found in '{sentence_fi}'")
            continue

        question_fi = sentence_fi.replace(target_fi, "....", 1)
        question_en = raw["sentence_en"].replace(target_en, "....", 1)

        # All options lowercase and shuffled
        options = [target_fi.lower(), d1.lower(), d2.lower(), d3.lower()]
        random.shuffle(options)

        cq = ChallengeQuestion(
            id=uuid.uuid4(),
            external_id=None,      # LLM questions have no quest-service ID
            source="llm",
            question_fi=question_fi,
            question_en=question_en,
            options=options,
            correct_answer=target_fi.lower(),
            difficulty=0.90,       # KELA is always Legendary tier
        )
        db.add(cq)
        questions.append(cq)

    await db.flush()
    return questions
