"""
Battle scenario definitions.

Each scenario controls:
  - which sentences get pulled from the DB (via scenario_tags)
  - difficulty range of those sentences
  - how many turns the battle lasts
  - rewards on victory
  - flavour text shown to the player during the fight

The kela_boss scenario is special - its challenges are generated by the
LLM based on the player's deck instead of pulled from the seed data.
"""

SCENARIOS: dict[str, dict] = {

    "cafe_order": {
        "name": "Ordering at Café Kulma",
        "description": (
            "A cosy Helsinki café. The barista is waiting. "
            "Order your drink before the queue builds up behind you."
        ),
        "tag": "cafe_order",
        "difficulty_min": 0.05,
        "difficulty_max": 0.70,
        "turns": 6,
        "xp_reward": 50,
        "bonus_packs": 1,
        "ai_wrong_answer": [
            "The barista raises an eyebrow. Wrong order.",
            "The customer behind you sighs loudly.",
            "You get oat milk. You did not ask for oat milk.",
            "The barista writes something down. It is not your order.",
        ],
        "victory_text": (
            "Kahvi saatu! You ordered perfectly. "
            "The barista almost smiled."
        ),
        "defeat_text": (
            "You leave with a mystery drink. "
            "At least it is hot."
        ),
    },

    "job_interview": {
        "name": "Interview at TechKorppi Oy",
        "description": (
            "A Finnish tech company. The interviewer has read your CV. "
            "Prove you can handle formal Finnish."
        ),
        "tag": "job_interview",
        "difficulty_min": 0.20,
        "difficulty_max": 0.90,
        "turns": 8,
        "xp_reward": 100,
        "bonus_packs": 2,
        "ai_wrong_answer": [
            "The interviewer writes something down. Not good.",
            "Awkward silence fills the room. Very Finnish.",
            "'Interesting,' they say. It is not a compliment.",
            "They glance at your CV again. Concern is visible.",
        ],
        "victory_text": (
            "Olet palkattu! You got the job. "
            "Impressive Finnish."
        ),
        "defeat_text": (
            "They will let you know. "
            "They will not."
        ),
    },

    "asking_directions": {
        "name": "Lost in Lahti",
        "description": (
            "You need the train station. "
            "A local is looking at you. "
            "Whether they help depends on your Finnish."
        ),
        "tag": "asking_directions",
        "difficulty_min": 0.08,
        "difficulty_max": 0.75,
        "turns": 6,
        "xp_reward": 75,
        "bonus_packs": 1,
        "ai_wrong_answer": [
            "They switch to English. Painful.",
            "They point vaguely. You are not sure which way.",
            "They give directions so fast you catch nothing.",
            "They walk away. You are still lost.",
        ],
        "victory_text": (
            "Löysit aseman! You found the station. "
            "On time, even."
        ),
        "defeat_text": (
            "You end up at the lake. "
            "It is actually quite nice."
        ),
    },

    "kela_boss": {
        "name": "KELA - The Final Form",
        "description": (
            "The Finnish Social Insurance Institution. "
            "Legendary compound nouns. Passive voice everywhere. "
            "Your forms must be correct. This is the hardest boss."
        ),
        "tag": "kela_boss",
        "difficulty_min": 0.60,
        "difficulty_max": 1.00,
        "turns": None,          # turns = deck_size - 2, calculated at runtime
        "xp_reward": 200,
        "bonus_packs": 3,
        "min_deck_size": 6,     # enforced before the battle starts
        "uses_llm": True,       # flags that challenges come from the LLM
        "ai_wrong_answer": [
            "Form rejected. Please refile within 14 days.",
            "The system requires the correct case suffix.",
            "Your application is under processing. Duration: undefined.",
            "A letter has been sent to your address. Good luck reading it.",
            "Please visit your nearest KELA office. Bring everything.",
        ],
        "victory_text": (
            "Hakemus hyväksytty! Application approved. "
            "A true Finnish miracle."
        ),
        "defeat_text": (
            "You receive a letter in Finnish. "
            "It requires a response in Finnish."
        ),
    },
}
