import enum
import uuid

from sqlalchemy import Float, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class BattleScenario(str, enum.Enum):
    CAFE_ORDER = "cafe_order"
    JOB_INTERVIEW = "job_interview"
    ASKING_DIRECTIONS = "asking_directions"
    KELA_BOSS = "kela_boss"


class BattleStatus(str, enum.Enum):
    ACTIVE = "active"
    WON = "won"
    LOST = "lost"
    DRAW = "draw"


class BattleSession(Base):
    """
    Tracks the full state of one PvE battle.

    Storing everything in the DB means the service stays stateless -
    any request can pick up exactly where the last one left off.

    For normal scenarios:
      - challenges are picked from the seed data filtered by scenario_tags
      - challenge_queue is a JSON list of Challenge UUIDs

    For kela_boss:
      - challenges are generated by the LLM based on the player's deck
      - same structure, different source
    """

    __tablename__ = "battle_sessions"

    # user_id from the Node.js backend
    user_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)

    scenario: Mapped[str] = mapped_column(String(64), nullable=False)

    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default=BattleStatus.ACTIVE
    )

    player_hp: Mapped[int] = mapped_column(Integer, nullable=False)
    ai_hp: Mapped[int] = mapped_column(Integer, nullable=False)

    # Which turn we are on, starts at 1
    current_turn: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    # Ordered list of Challenge UUIDs for this battle, as a JSON array of strings
    # e.g. ["uuid1", "uuid2", "uuid3", ...]
    challenge_queue: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    # The player's deck as sent by Node.js
    # e.g. [{"card_id": "...", "rarity": "Rare", "word_fi": "teetä", "power": 20}]
    deck: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    # Accumulated XP for this battle, increases each turn
    xp_earned: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Bonus packs awarded on victory
    bonus_packs: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    def __repr__(self) -> str:
        return (
            f"<BattleSession scenario={self.scenario} "
            f"status={self.status} "
            f"turn={self.current_turn} "
            f"player_hp={self.player_hp} ai_hp={self.ai_hp}>"
        )


class BattleAction(Base):
    """
    Logs every turn in a battle.
    One row per turn - useful for replays, debugging, and stats.
    """

    __tablename__ = "battle_actions"

    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )

    turn: Mapped[int] = mapped_column(Integer, nullable=False)

    challenge_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )

    # What the player picked from the 4 options
    given_answer: Mapped[str] = mapped_column(Text, nullable=False)

    is_correct: Mapped[bool] = mapped_column(nullable=False, default=False)

    # Damage dealt to the AI this turn (0 if wrong answer)
    damage_dealt: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Damage taken from the AI this turn (0 if correct answer)
    damage_taken: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    def __repr__(self) -> str:
        return (
            f"<BattleAction turn={self.turn} "
            f"correct={self.is_correct} "
            f"dealt={self.damage_dealt} taken={self.damage_taken}>"
        )
