import enum
import uuid

from sqlalchemy import Float, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class ChallengeScenario(str, enum.Enum):
    CAFE_ORDER       = "cafe_order"
    JOB_INTERVIEW    = "job_interview"
    ASKING_DIRECTIONS = "asking_directions"
    KELA_BOSS        = "kela_boss"


class ChallengeStatus(str, enum.Enum):
    ACTIVE = "active"
    WON    = "won"
    LOST   = "lost"
    DRAW   = "draw"


class ChallengeSession(Base):
    """
    Tracks the full state of one PvE boss fight (Challenge).

    The question queue is built entirely at start time — each request
    just reads from it so the service stays stateless mid-fight.

    For normal scenarios:
      - questions are fetched from Quest Service (8001) via HTTP
      - question_queue is a JSON list of local ChallengeQuestion UUIDs

    For kela_boss:
      - questions are generated by the LLM boss using the player's deck
      - same structure, different source
    """

    __tablename__ = "challenge_sessions"

    user_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    scenario: Mapped[str] = mapped_column(String(64), nullable=False)

    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default=ChallengeStatus.ACTIVE
    )

    player_hp: Mapped[int] = mapped_column(Integer, nullable=False)
    ai_hp: Mapped[int] = mapped_column(Integer, nullable=False)

    # Which turn we are on, starts at 1
    current_turn: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    # Ordered list of ChallengeQuestion UUIDs for this boss fight
    question_queue: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    # The player's deck as sent by Node.js
    deck: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    xp_earned: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    bonus_packs: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    def __repr__(self) -> str:
        return (
            f"<ChallengeSession scenario={self.scenario} "
            f"status={self.status} turn={self.current_turn} "
            f"player_hp={self.player_hp} ai_hp={self.ai_hp}>"
        )


class ChallengeAction(Base):
    """
    Logs every turn in a boss fight.
    One row per turn — useful for replays, debugging, and stats.
    """

    __tablename__ = "challenge_actions"

    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )

    turn: Mapped[int] = mapped_column(Integer, nullable=False)

    question_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )

    given_answer: Mapped[str] = mapped_column(Text, nullable=False)
    is_correct: Mapped[bool] = mapped_column(nullable=False, default=False)

    # Damage dealt to the AI this turn (0 if wrong answer)
    damage_dealt: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Damage taken from the AI this turn (0 if correct answer)
    damage_taken: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    def __repr__(self) -> str:
        return (
            f"<ChallengeAction turn={self.turn} "
            f"correct={self.is_correct} "
            f"dealt={self.damage_dealt} taken={self.damage_taken}>"
        )
