"""
ChallengeQuestion model.

Challenge Service stores ALL questions used in boss fights locally in this table.
This keeps the boss fight self-contained after start — get_next_question always
reads from here, never calls back to Quest Service mid-fight.

Two sources:
  1. Normal boss fights  → fetched from Quest Service (8001) via HTTP at fight start,
                           mirrored here as ChallengeQuestion rows. source="quest_service"
  2. KELA LLM boss       → generated by Claude at fight start, stored directly here.
                           source="llm"

The question_queue in ChallengeSession stores UUIDs of ChallengeQuestion rows.
"""

import uuid

from sqlalchemy import Float, String, Text
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class ChallengeQuestion(Base):
    """
    A question scoped to a specific boss fight session.

    Mirrors the Quest schema from the Quest Service but lives in the
    Challenge Service DB so fights never depend on Quest Service being
    up mid-fight.
    """

    __tablename__ = "challenge_questions"

    # UUID the Quest Service assigned (None for LLM-generated questions)
    external_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
        index=True,
    )

    # "quest_service" | "llm"
    source: Mapped[str] = mapped_column(String(32), nullable=False, default="quest_service")

    question_fi: Mapped[str] = mapped_column(Text, nullable=False)
    question_en: Mapped[str] = mapped_column(Text, nullable=False)

    # 4 options shown to the player, already shuffled
    options: Mapped[list] = mapped_column(ARRAY(String), nullable=False)

    # Never sent to frontend before submission
    correct_answer: Mapped[str] = mapped_column(String(256), nullable=False)

    difficulty: Mapped[float] = mapped_column(Float, nullable=False)

    def __repr__(self) -> str:
        return (
            f"<ChallengeQuestion source={self.source} "
            f"correct='{self.correct_answer}' difficulty={self.difficulty}>"
        )
